/**
 * This Java Class is part of the RBM-provisor Application
 * which, in turn, is part of the Intelligent Music Software
 * project at Harvey Mudd College, under the directorship of Robert Keller.
 *
 * Copyright (C) 2009 Robert Keller and Harvey Mudd College
 *
 * RBM-provisor is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * RBM-provisor is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * merchantability or fitness for a particular purpose.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RBM-provisor; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */


/*
 * ProgressBars.java
 *
 * Created on Jul 14, 2009, 10:17:56 AM
 */

package rbm;

/**
 *
 * @author Sam Bosley
 */
public class ProgressBars extends javax.swing.JPanel {

    /** Creates new form ProgressBars */
    public ProgressBars() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        actionDescription = new javax.swing.JLabel();
        progressDescription = new javax.swing.JLabel();
        partialProgressBar = new javax.swing.JProgressBar();
        overallProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Progress"));
        setMinimumSize(new java.awt.Dimension(300, 125));
        setPreferredSize(new java.awt.Dimension(300, 125));
        setLayout(new java.awt.GridBagLayout());

        actionDescription.setText("<Action description>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(actionDescription, gridBagConstraints);

        progressDescription.setText("<Progress description>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(progressDescription, gridBagConstraints);

        partialProgressBar.setMinimumSize(new java.awt.Dimension(250, 20));
        partialProgressBar.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(partialProgressBar, gridBagConstraints);

        overallProgressBar.setMinimumSize(new java.awt.Dimension(250, 20));
        overallProgressBar.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(overallProgressBar, gridBagConstraints);

        jLabel1.setText("Overall progress:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    public void setActionDescription(String text) {
        actionDescription.setText(text);
    }

    public void setProgressDescription(String text) {
        progressDescription.setText(text);
    }

    public void setPartialBarRange(int min, int max) {
        partialProgressBar.setMinimum(min);
        partialProgressBar.setMaximum(max);
    }

    public void setOverallBarRange(int min, int max) {
        overallProgressBar.setMinimum(min);
        overallProgressBar.setMaximum(max);
    }

    public void setPartialProgress(int n) {
        partialProgressBar.setValue(n);
    }

    public void setOverallProgress(int n) {
        overallProgressBar.setValue(n);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar overallProgressBar;
    private javax.swing.JProgressBar partialProgressBar;
    private javax.swing.JLabel progressDescription;
    // End of variables declaration//GEN-END:variables

}
